### ISSUE TITLE
ValueError: math domain error

### ISSUE THREAD

**Issue by eagle-star** [zhanzecheng/Chinese_segment_augment#1]
PMI计算出现不符合数学规则的计算

**Comment by zhanzecheng** [comment]
能详细一点么，具体是那个部分出错了？

**Comment by LeonSCZ** [comment]
所有的除法计算里面，给除数或者被除数加上float()。

**Comment by LeonSCZ** [comment]
好像没有考虑三元词组的计算？比如分词结果是A,B,C这三个词组成ABC。

**Comment by LeonSCZ** [comment]
@liueagle  所有的除法计算里面，给除数或者被除数加上float()。

**Comment by zhanzecheng** [comment]
@LeonSCZ 是的，就是只考虑了二元的情况

**Comment by LeonSCZ** [comment]
可以给个邮箱交流下么？

**Comment by LeonSCZ** [comment]
@zhanzecheng ， 文件model.py里面第194行是不是有点问题，是否应该改成 if ch.word_dinnish == True ？烦请解释一下。

**Comment by zhanzecheng** [comment]
@LeonSCZ 是的，已修改

**Comment by LeonSCZ** [comment]
@zhanzecheng 其实我想交流下，对于三元短语和四元短语 具体到应用词典树怎么算？我关心的问题：
1. 例如对于3gram的情况下，你转换了ABC--->BCA，那么对于4gram和5gram要做什么转变，之所以提到5gram是因为，要是别4元短语，是不是要考虑到5gram？
2. 对于3gram和4gram，其互信息怎么计算？

**Comment by UCASREN** [comment]
我也是上述疑问：

我查了，好像互信息就是指两个变量间的计算，那么，对于3gram和4gram的互信息计算公式是什么？是不是可以转化成2gram的互信息计算，该怎么转化？这方面有前人的研究吗？

求解答~

**Comment by UCASREN** [comment]
@zhanzecheng @LeonSCZ
