### ISSUE TITLE
直接线性加和是最好的方法吗？

### ISSUE THREAD

**Issue by tuzhe0210** [zhanzecheng/Chinese_segment_augment#13]
个人也写过一个类似的东东，尝试过几种左右熵和互信息的结合方式都不是很满意，请问还有更好的方法吗，尝试过加权和比值的多种参数。

**Comment by zhanzecheng** [comment]
Hi tuzhe0210,

目前我这里尝试过的加权加和直接线性加，但由于新词这块还没有写好评价指标，暂时没有区分孰优孰劣。另外由于便于理解，这里就直接采用线性加的方式了。
更加复杂的操作可能会取得更优的结果。

Best,
Zecheng
