### ISSUE TITLE
‘加载外部词频记录 dict.txt ’  的作用是啥啊？

### ISSUE THREAD

**Issue by zhangrenjie666666** [zhanzecheng/Chinese_segment_augment#17]
‘加载外部词频记录 dict.txt ’  的作用是啥啊？

**Comment by zhanzecheng** [comment]
dict.txt 先验的词表。因为我们需要统计每一个词在真实环境中出现的概率，只用待发现新词的文本并不能很准确的反映一个词的概率，需要外部大词典来统计。

**Comment by zhangrenjie666666** [comment]
您好！
就是说dict词典 是用来纠错的？那么
1：dict词典 是基于什么语料来统计的呢？
2：dict词典中已经有词的概率，而待训练文本中 也有一个词频，两者会不会冲突影响结果呢？

> dict.txt先验的词表。因为我们需要统计每一个词在真实环境中出现的概率，只用待发现新词的文本并不能很准确的反映一个词的概率，需要外部大词典来统计。
