### ISSUE TITLE
程序下载后无法正常运行

### ISSUE THREAD

**Issue by hiber-niu** [zhanzecheng/Chinese_segment_augment#6]
主要问题有两个：
1. 在加载文件时，文件路径错误。
demo_run.py 43/48行缺少"/"
2. 修改后文件model.py 84行：
   word[0], word[1], word[2] = word[1], word[2], word[0]
TypeError: 'tuple' object does not support item assignment

**Comment by hiber-niu** [comment]
将问题2转换成list处理后，程序无法返回有效的结果。会返回空的result。

**Comment by hiber-niu** [comment]
@zhanzecheng 已提交request更新。

**Comment by zhanzecheng** [comment]
Thanks a lot @hiber-niu
